import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Copy, Check, Plus, Settings, LogOut, Link as LinkIcon, QrCode, Trash2, Power, Menu, X, ShieldCheck, RefreshCw, Eye, EyeOff, RotateCcw, ExternalLink, Activity, Clock3, DatabaseZap} from 'lucide-react';
import './style.css';

const fmt = n => {
  if (n == null) return '∞';
  let v = Number(n || 0); const u = ['B','KB','MB','GB','TB']; let i = 0;
  while (v >= 1024 && i < u.length - 1) { v /= 1024; i++; }
  return i === 0 ? `${Math.round(v)} B` : `${v < 10 ? v.toFixed(1) : v.toFixed(0)} ${u[i]}`;
};
const fmtDate = ts => ts ? new Intl.DateTimeFormat('fa-IR',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(ts)) : '∞';
const api = (path,opt={}) => fetch(path,{...opt,credentials:'same-origin',headers:{'content-type':'application/json',...(opt.headers||{})}}).then(async r=>{const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'خطا در ارتباط با سرور');return j});

function Login({onLogin}) {
  const [password,setPassword]=useState(''),[show,setShow]=useState(false),[err,setErr]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setErr('');setBusy(true);try{await api('/api/login',{method:'POST',body:JSON.stringify({username:'admin',password})});onLogin()}catch(e){setErr(e.message)}finally{setBusy(false)}}
  return <div className="login"><div className="loginBox"><div className="logo"><b>Vodi <span>VPN</span></b></div><div className="mark">V</div><div className="eyebrow">SECURE ADMIN</div><h1>ورود به پنل</h1><p>مدیریت ساده و سریع VLESS</p><form onSubmit={submit}><label>رمز عبور ادمین</label><div className="input eye"><input autoFocus type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="رمز عبور" required/><button type="button" aria-label="نمایش رمز" onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div>{err&&<div className="error">{err}</div>}<button className="primary wide" disabled={busy}>{busy?'در حال ورود…':'ورود'}</button></form><small>ورود اولیه: <b>admin / admin</b></small></div></div>;
}

function App(){
  const [logged,setLogged]=useState(false),[data,setData]=useState(null),[page,setPage]=useState('dash'),[modal,setModal]=useState(false),[mobileNav,setMobileNav]=useState(false);
  async function load(){try{setData(await api('/api/bootstrap'));setLogged(true)}catch{setData(null);setLogged(false)}}
  useEffect(()=>{load()},[]);
  if(!logged)return <Login onLogin={load}/>;
  if(!data)return <div className="loading"><Activity className="spin"/> در حال آماده‌سازی…</div>;
  const nav=p=>{setPage(p);setMobileNav(false)};
  return <div className="shell" dir="rtl"><aside><div className="brand">Vodi <span>VPN</span></div><nav><button className={page==='dash'?'active':''} onClick={()=>nav('dash')}><Activity size={17}/>داشبورد</button><button className={page==='configs'?'active':''} onClick={()=>nav('configs')}><LinkIcon size={17}/>کانفیگ‌ها</button><button className={page==='settings'?'active':''} onClick={()=>nav('settings')}><Settings size={17}/>تنظیمات</button></nav><div className="sideBottom"><span><i className={data.nodes[0]?.status==='online'?'onlineDot':''}/>{data.nodes[0]?.name} · {data.nodes[0]?.status==='online'?'آنلاین':'آفلاین'}</span><button onClick={async()=>{await api('/api/logout',{method:'POST'});setLogged(false);setData(null)}}><LogOut size={16}/> خروج</button></div></aside><main><header><button className="mobileMenu" onClick={()=>setMobileNav(!mobileNav)}><Menu size={20}/></button><span>Vodi VPN</span><div className="headerStatus"><ShieldCheck size={17}/> VLESS + WebSocket</div></header>{mobileNav&&<div className="mobileNav"><button onClick={()=>nav('dash')}>داشبورد</button><button onClick={()=>nav('configs')}>کانفیگ‌ها</button><button onClick={()=>nav('settings')}>تنظیمات</button></div>}{page==='dash'?<Dashboard data={data} create={()=>setModal(true)} goConfigs={()=>setPage('configs')}/>:page==='configs'?<Configs data={data} create={()=>setModal(true)} reload={load}/>:<SettingsPage data={data} reload={load}/>}</main>{modal&&<CreateModal close={()=>setModal(false)} done={()=>{setModal(false);load()}}/>}</div>;
}

function Dashboard({data,create,goConfigs}){const active=data.configs.filter(c=>c.enabled&&!c.expired).length;const totalUsed=data.configs.reduce((s,c)=>s+Number(c.usedBytes||0),0);return <section className="page"><div className="titleRow"><div><small>VODI VPN</small><h1>داشبورد</h1><p>یک پنل خلوت برای ساخت و مدیریت VLESS.</p></div><button className="primary" onClick={create}><Plus size={18}/> ساخت کانفیگ جدید</button></div><div className="stats"><div><span>کانفیگ فعال</span><b>{active}</b></div><div><span>مصرف ثبت‌شده</span><b>{fmt(totalUsed)}</b></div><div><span>وضعیت سرویس</span><b className="statusText"><i className={data.nodes[0]?.status==='online'?'onlineDot':''}/>{data.nodes[0]?.status==='online'?'Online':'Offline'}</b></div></div><div className="hero"><div><small>VLESS / WEBSOCKET</small><h2>ساخت خودکار، بدون شلوغی</h2><p>حجم و مدت را انتخاب کن؛ UUID، لینک VLESS و Subscription ساخته می‌شود.</p><button className="outline" onClick={create}>⚡ ساخت کانفیگ</button></div><div className="heroBadge">V</div></div><div className="recent"><div className="sectionHead"><h2>آخرین کانفیگ‌ها</h2><button onClick={goConfigs}>مشاهده همه</button></div>{data.configs.slice(0,4).map(c=><Mini key={c.id} c={c}/>)}{!data.configs.length&&<div className="empty compact"><h2>هنوز کانفیگی ساخته نشده</h2><p>اولین کانفیگ VLESS خودت را بساز.</p></div>}</div></section>}
function Mini({c}){return <div className="mini"><div><b>{c.name}</b><span>{c.enabled&&!c.expired?'فعال':'غیرفعال'}</span></div><strong>{fmt(c.usedBytes||0)} / {c.volumeGB?`${c.volumeGB} GB`:'∞'}</strong></div>}

function Configs({data,create,reload}){return <section className="page"><div className="titleRow"><div><small>VLESS</small><h1>کانفیگ‌ها</h1><p>هر کانفیگ یک UUID و Subscription مستقل دارد.</p></div><button className="primary" onClick={create}><Plus size={18}/> ساخت کانفیگ</button></div>{data.configs.map(c=><Config key={c.id} c={c} reload={reload}/>)}{!data.configs.length&&<div className="empty"><LinkIcon size={30}/><h2>هنوز کانفیگی ساخته نشده</h2><p>اولین کانفیگ VLESS خودت را بساز.</p></div>}</section>}

function Config({c,reload}){
  const [copy,setCopy]=useState(''),[qr,setQr]=useState(false),[busy,setBusy]=useState(false);
  const remain=c.expiresAt?Math.max(0,Math.ceil((c.expiresAt-Date.now())/86400000)):null;
  async function action(path,opt){setBusy(true);try{await api(path,opt);await reload()}catch(e){alert(e.message)}finally{setBusy(false)}}
  async function copyText(text,key){try{await navigator.clipboard.writeText(text);setCopy(key);setTimeout(()=>setCopy(''),1200)}catch{alert('کپی خودکار در دسترس نیست')}}
  return <article className="config"><div className="configHead"><div><b>{c.name}</b><span className={c.enabled&&!c.expired?'ok':''}>{c.enabled&&!c.expired?'فعال':'غیرفعال'}</span></div><strong>VLESS / WS</strong></div><div className="configStats"><div><small>مصرف</small><b>{fmt(c.usedBytes||0)} / {c.volumeGB?`${c.volumeGB} GB`:'∞'}</b></div><div><small>انقضا</small><b>{remain==null?'∞':`${remain} روز`}</b></div><div><small>دستگاه</small><b>∞</b></div></div><div className="link"><input readOnly value={c.link}/><button onClick={()=>copyText(c.link,'vless')}>{copy==='vless'?<Check size={17}/>:<Copy size={17}/>}</button></div><div className="subRow"><span>Subscription</span><input readOnly value={c.subscriptionRaw}/><button onClick={()=>copyText(c.subscriptionRaw,'sub')}>{copy==='sub'?<Check size={16}/>:<Copy size={16}/>}</button><a href={c.subscriptionPage} target="_blank" rel="noreferrer"><ExternalLink size={16}/></a></div><div className="actions"><button onClick={()=>setQr(!qr)}><QrCode size={16}/> QR</button><button disabled={busy} onClick={()=>action(`/api/configs/${c.id}/reset`,{method:'POST'})}><RotateCcw size={16}/> Reset مصرف</button><button disabled={busy} onClick={()=>action(`/api/configs/${c.id}`,{method:'PATCH',body:JSON.stringify({enabled:!c.enabled})})}><Power size={16}/> {c.enabled?'خاموش':'روشن'}</button><button className="danger" disabled={busy} onClick={()=>confirm('این کانفیگ حذف شود؟')&&action(`/api/configs/${c.id}`,{method:'DELETE'})}><Trash2 size={16}/></button></div>{qr&&<div className="qrBox"><img src={c.subscriptionPage.replace(/\/sub\//,'/sub/').replace(/\/?$/,'')+'/qr'} alt="QR"/><p>برای VLESS یا Subscription اسکن کن.</p></div>}</article>;
}

function CreateModal({close,done}){const[f,setF]=useState({name:`Vodi-${Math.random().toString(36).slice(2,7).toUpperCase()}`,volumeGB:'50',days:'30'}),[err,setErr]=useState(''),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setErr('');setBusy(true);try{await api('/api/configs',{method:'POST',body:JSON.stringify(f)});done()}catch(e){setErr(e.message)}finally{setBusy(false)}}return <div className="overlay"><div className="modal"><button className="close" onClick={close}><X/></button><div className="eyebrow">NEW CONFIG</div><h2>ساخت کانفیگ جدید</h2><p>فقط VLESS + WebSocket · مسیر پیش‌فرض /vless</p><form onSubmit={submit}><label>نام<input autoFocus value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>حجم (GB)<input type="number" min="1" step="0.1" value={f.volumeGB} onChange={e=>setF({...f,volumeGB:e.target.value})}/><small>برای نامحدود خالی بگذار.</small></label><label>مدت (روز)<input type="number" min="1" value={f.days} onChange={e=>setF({...f,days:e.target.value})}/><small>برای نامحدود خالی بگذار.</small></label>{err&&<div className="error">{err}</div>}<button className="primary wide" disabled={busy}>{busy?'در حال ساخت…':'ساخت خودکار'}</button></form></div></div>}

function SettingsPage({data,reload}){const[p,setP]=useState({currentPassword:'',newPassword:'',confirmPassword:''}),[msg,setMsg]=useState(''),[show,setShow]=useState(false);async function change(e){e.preventDefault();try{await api('/api/change-password',{method:'POST',body:JSON.stringify(p)});setMsg('رمز با موفقیت تغییر کرد.');setTimeout(()=>location.reload(),700)}catch(e){setMsg(e.message)}}async function save(){const host=document.getElementById('host').value,path=document.getElementById('path').value;try{await api('/api/settings',{method:'POST',body:JSON.stringify({publicHost:host,wsPath:path})});setMsg('تنظیمات ذخیره شد.');reload()}catch(e){setMsg(e.message)}}return <section className="page"><div className="titleRow"><div><small>SETTINGS</small><h1>تنظیمات</h1><p>فقط تنظیمات ضروری؛ بدون شلوغی.</p></div></div><div className="settingsGrid"><div className="settingCard"><div className="cardIcon"><DatabaseZap size={18}/></div><h2>VLESS / WebSocket</h2><p className="muted">دامنه خالی باشد، آدرس عمومی درخواست Railway استفاده می‌شود.</p><label>دامنه عمومی<input id="host" defaultValue={data.settings.publicHost||''} placeholder="example.com"/></label><label>مسیر WebSocket<input id="path" defaultValue={data.settings.wsPath||'/vless'}/></label><button className="primary" onClick={save}>ذخیره تنظیمات</button></div><div className="settingCard"><div className="cardIcon"><Settings size={18}/></div><h2>حساب مدیر</h2><p className="muted">نام کاربری ثابت: <b>admin</b></p><form onSubmit={change}><label>رمز فعلی<input type={show?'text':'password'} value={p.currentPassword} onChange={e=>setP({...p,currentPassword:e.target.value})}/></label><label>رمز جدید<input type={show?'text':'password'} value={p.newPassword} onChange={e=>setP({...p,newPassword:e.target.value})}/></label><label>تکرار رمز جدید<input type={show?'text':'password'} value={p.confirmPassword} onChange={e=>setP({...p,confirmPassword:e.target.value})}/></label><button type="button" className="ghost" onClick={()=>setShow(!show)}>{show?'مخفی کردن رمز':'نمایش رمز'}</button><button className="primary">تغییر رمز</button></form></div></div>{msg&&<div className="notice">{msg}</div>}</section>}

function SubscriptionPage(){const token=location.pathname.split('/')[2];const[data,setData]=useState(null),[err,setErr]=useState(''),[copied,setCopied]=useState(false);useEffect(()=>{fetch(`/sub/${token}/meta`).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error||'اشتراک پیدا نشد');setData(j)}).catch(e=>setErr(e.message))},[token]);if(err)return <div className="subPage"><div className="subCard"><div className="mark">V</div><h1>Subscription پیدا نشد</h1><p>{err}</p></div></div>;if(!data)return <div className="loading"><Activity className="spin"/> در حال دریافت اشتراک…</div>;const remain=data.expiresAt?Math.max(0,Math.ceil((data.expiresAt-Date.now())/86400000)):null;const copy=async()=>{await navigator.clipboard.writeText(data.raw);setCopied(true);setTimeout(()=>setCopied(false),1200)};return <div className="subPage" dir="rtl"><div className="subWrap"><div className="subBrand">Vodi <span>VPN</span></div><div className="subCard"><div className="subTop"><div><small>VODI SUBSCRIPTION</small><h1>{data.name}</h1><p>{data.enabled?'اشتراک فعال است':'اشتراک غیرفعال است'}</p></div><div className={`state ${data.enabled?'good':''}`}>{data.enabled?'ACTIVE':'OFF'}</div></div><div className="subStats"><div><small>مصرف</small><b>{fmt(data.usedBytes)} / {data.volumeGB==null?'∞':`${data.volumeGB} GB`}</b></div><div><small>انقضا</small><b>{remain==null?'∞':`${remain} روز`}</b></div><div><small>دستگاه</small><b>∞</b></div></div><div className="usage"><div><span>مصرف</span><b>{data.volumeGB==null?'نامحدود':`${Math.min(100,(data.usedBytes/(data.volumeGB*1024**3))*100).toFixed(1)}%`}</b></div><div className="bar"><i style={{width:data.volumeGB==null?'0%':`${Math.min(100,(data.usedBytes/(data.volumeGB*1024**3))*100)}%`}}/></div></div><div className="subLink"><input readOnly value={data.raw}/><button onClick={copy}>{copied?<Check size={18}/>:<Copy size={18}/>}</button></div><div className="subActions"><a href={data.raw}>باز کردن لینک</a><button onClick={copy}>{copied?'کپی شد':'کپی لینک'}</button></div><div className="subQr"><img src={data.qr} alt="QR Code"/><p>QR را در کلاینت سازگار اسکن کن.</p></div><div className="subMeta"><span>VLESS</span><span>WebSocket</span><span>{data.volumeGB==null?'∞':`${data.volumeGB} GB`}</span><span>{data.expiresAt?fmtDate(data.expiresAt):'∞'}</span></div></div><p className="subFoot">Vodi VPN · Subscription</p></div></div>}

const isSub=/^\/sub\/[^/]+$/.test(location.pathname);
createRoot(document.getElementById('root')).render(isSub?<SubscriptionPage/>:<App/>);
